In [38]:
import pandas as pd
import numpy as np

In [2]:
traindata = pd.read_csv('labeledTrainData.tsv',delimiter='\t',encoding='utf-8')

In [3]:
traindata.head()

id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2  7759_3          0  The film starts with a manager (Nicholas Bell)...
3  3630_4          0  It must be assumed that those who praised this...
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...

In [4]:
traindata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 3 columns):
id           25000 non-null object
sentiment    25000 non-null int64
review       25000 non-null object
dtypes: int64(1), object(2)
memory usage: 586.0+ KB


In [7]:
testdata=pd.read_csv('testData.tsv',delimiter='\t',encoding='utf-8')
testdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 2 columns):
id        25000 non-null object
review    25000 non-null object
dtypes: object(2)
memory usage: 390.7+ KB


In [8]:
from sklearn.feature_extraction.text import CountVectorizer

Co=CountVectorizer()
bag=Co.fit_transform(testdata.review)
bag

<25000x73822 sparse matrix of type '<class 'numpy.int64'>'
	with 3380668 stored elements in Compressed Sparse Row format>

In [9]:
Co.get_feature_names()

['00',
 '000',
 '00000000000',
 '00000001',
 '000dm',
 '001',
 '0069',
 '007',
 '0079',
 '007s',
 '0083',
 '009',
 '00am',
 '00o',
 '00pm',
 '00s',
 '00schneider',
 '01',
 '0126',
 '0148',
 '02',
 '0230',
 '03',
 '039',
 '04',
 '044',
 '05',
 '05nomactr',
 '06',
 '0615',
 '07',
 '07b',
 '08',
 '08th',
 '09',
 '0and',
 '0f',
 '0tt',
 '10',
 '100',
 '1000',
 '10000',
 '1000000',
 '10000000000',
 '10000000000000',
 '10000th',
 '1000s',
 '1000th',
 '1001',
 '1004',
 '100bt',
 '100ft',
 '100ibs',
 '100k',
 '100miles',
 '100mins',
 '100s',
 '100th',
 '100times',
 '100x',
 '101',
 '101st',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '1080',
 '1080p',
 '109',
 '10_',
 '10ft',
 '10ish',
 '10k',
 '10mins',
 '10minutes',
 '10pm',
 '10s',
 '10th',
 '10x',
 '10yo',
 '10yr',
 '10yrs',
 '11',
 '110',
 '110min',
 '110mph',
 '111',
 '112',
 '113',
 '1138',
 '113min',
 '113minutes',
 '115',
 '116',
 '116minutes',
 '117',
 '11706',
 '118',
 '119',
 '11am',
 '11th',
 '11ths',
 '11yr',
 '12',


In [10]:
bag.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [11]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer()
np.set_printoptions(precision=2)
x = tfidf.fit_transform(bag)
x.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
Y = vectorizer.fit_transform(testdata.review)
Y.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
from collections import Counter

vocab = Counter()
traindata['review']

for line in traindata['review']:
    #line.split()
    for word in line.split():
        vocab[word]+=1

In [14]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/phamkhanhduy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [15]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

vocab_reduced = Counter()

In [16]:
for line in traindata['review']:
    #line.split()
    for word in line.split():
        if word not in stop:
            vocab_reduced[word]+=1

In [42]:
import re

In [43]:
def preprocessor(text):
    """ Return a cleaned version of text
    """
    # Remove HTML markup
    text = re.sub('<[^>]*>', '', text)
    # Save emoticons for later appending
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    # Remove any non-word character and append the emoticons,
    # removing the nose character for standarization. Convert to lower case
    text = (re.sub('[\W]+', ' ', text.lower()) + ' ' + ' '.join(emoticons).replace('-', ''))
    
    return text

In [44]:
from nltk.stem import PorterStemmer

porter = PorterStemmer()

# write a function called `tokenizer()` that split a text into list of words
# Your code here
def tokenizer(text):
    return text.split()


# write a function named `tokenizer_porter()` that split a text into list of words and apply stemming technic
# Hint: porter.stem(word)
# Your code here
def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

In [45]:
X = traindata['review']
y = traindata['sentiment']
# y = sentiment[['SentimentText']]
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [46]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

In [47]:
tfidf = TfidfVectorizer(stop_words=stop,
                        tokenizer=tokenizer_porter,
                        preprocessor=preprocessor)

In [48]:
clf = Pipeline([('vect', tfidf),
                ('clf', LogisticRegression(random_state=0))])
clf.fit(X_train, y_train)

/Users/phamkhanhduy/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py:286: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'ani', 'becaus', 'befor', 'doe', 'dure', 'ha', 'hi', 'onc', 'onli', 'ourselv', 'themselv', 'thi', 'veri', 'wa', 'whi', 'yourselv'] not in stop_words.
  sorted(inconsistent))
/Users/phamkhanhduy/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2',
        preprocessor=<function prepr...e, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False))])

In [52]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [63]:
prediction = clf.predict(X_test)

a_s = accuracy_score(y_test,prediction)
a_s
cm = confusion_matrix(y_test,prediction)
cm
cr = classification_report(y_test, prediction)
print (cr)

              precision    recall  f1-score   support

           0       0.90      0.87      0.89      2518
           1       0.87      0.91      0.89      2482

   micro avg       0.89      0.89      0.89      5000
   macro avg       0.89      0.89      0.89      5000
weighted avg       0.89      0.89      0.89      5000



In [65]:
preds = clf.predict_proba(testdata.review)

for i in range(len(testdata.review)):
    print(f'{testdata[i]} --> Negative, Positive = {preds[i]}')

KeyError: 0

In [72]:
import pickle
import so

#pickle.dump(clf, open(os.path.join('data', 'logisticRegression.pkl'), 'wb'), protocol=4)

ModuleNotFoundError: No module named 'so'